{{ if and (.Values.backingStoreConfig.deployment.deployStore) (eq .Values.backingStoreConfig.KONG_DATABASE "cassandra") }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.backingStoreConfig.KONG_CASSANDRA_CONTACT_POINTS }}
spec:
  ports:
  - name: cql
    port: 9042
    targetPort: 9042
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.backingStoreConfig.deployment.storeDeploymentName }}

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Release.Name }}-{{ .Values.backingStoreConfig.deployment.storeDeploymentName }}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.backingStoreConfig.deployment.storeDeploymentName }}
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.5
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SEED_PROVIDER
              value: "io.k8s.cassandra.KubernetesSeedProvider"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: gcr.io/google-samples/cassandra:v11
          name: cassandra
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}

{{ end }}